### ISSUE TITLE
Partially hidden faction image in the faction selection list

### ISSUE THREAD

**Issue by MHostile** [EwenDC/root-automated-setup#15]
In the "Choose Faction" step, the image of the first faction in the horizontal overflow of the faction selection list is partially hidden.

Reproduced on Google Chrome 103 for Windows and Android. The window width needs to be smaller than the the faction select list width to reproduce.
![Capture d’écran 2022-07-05 144713](https://user-images.githubusercontent.com/15193230/177332312-3fe4bec2-3bb3-4cd7-b2a7-e69b2be139d9.png)
![Capture d’écran 2022-07-05 144743](https://user-images.githubusercontent.com/15193230/177332337-24016473-a125-46a4-a8cb-ea153178050e.png)
![Capture d’écran 2022-07-05 144821](https://user-images.githubusercontent.com/15193230/177332358-5c9370f8-1479-4939-942b-a305bcbfe7e4.png)

**Comment by EwenDC** [comment]
Wasn't able to replicate on my desktop but was on my phone. Unfortunately it's quite likely to be a chrome bug which I have no ability to resolve. I'll look into this when I have time but chances are I'll have to close this issue and we'll have to hope for chrome to release a fix.

**Comment by EwenDC** [comment]
Good news! Found out there was a way to work around the chrome bug so now it's rendering correctly.
