### ISSUE TITLE
New French translation strings 2022-10-23

### ISSUE THREAD

**Issue by EwenDC** [EwenDC/root-automated-setup#19]
@MHostile The following strings have been added to the app, requiring a French translation:
![image](https://user-images.githubusercontent.com/39972488/197374890-5b355675-de27-4503-9dd0-9814dc42d4c9.png)
![image](https://user-images.githubusercontent.com/39972488/197374903-f6a6a6f2-dc6a-4fc4-930d-68977a7e51df.png)

Feel free to create a pull request with the new strings or just comment them on this issue and I'll add them to the app.

**Comment by MHostile** [comment]
I just created a pull request for this change: #20.

Thank you for the notification.

**Comment by EwenDC** [comment]
Thanks for the quick turnaround! Merged.
